theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: hero
  search:
    active: true
  breadcrumb:
    position: hero-start
    footer:
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logowhite.svg"   
  menu:
    dropdown:
      linkToLevel1: true
