theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: thesufficiencylab.org
  summary:
    position: hero
  search:
    active: true
  breadcrumb:
    position: hero-start
    footer:
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logowhite.svg"   
  menu:
    dropdown:
      linkToLevel1: true

  posts:
    index:
      layout: grid
