theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: hero
  search:
    active: false
  breadcrumb:
    position: hero-start
    footer:
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logowhite.svg"   
